add the clang-tidy CI check
AMReX-Astro/Microphysics pull request #1137
Opened 2023-03-02 01:05 UTC by zingale

2023-03-02 19:16 UTC, yut23 requested changes

2023-03-02 19:16 UTC, yut23 commented on .github/workflows/c-linter.yml
> +          header_filter: 'Microphysics'
This should match any headers ending with `.H` in any of the source directories or the build directory (`^./`). GCEM uses `.hpp` for its headers, so this ignores any warnings from there.
```suggestion
          header_filter: '(/conductivity/|/constants/|/EOS/|/integration/|/interfaces/|/networks/|/neutrinos/|/nse_solver/|/opacity/|/rates/|/screening/|/util/|^\./).*\.H$'
```

2023-03-03 00:21 UTC, zingale commented on .github/workflows/c-linter.yml
> +          header_filter: 'Microphysics'
this has been updated

2023-03-03 00:23 UTC, yut23 approved these changes

2023-03-03 00:32 UTC, merged