[WIP] use multiple angle formula in sneut to speed up sin/cos
AMReX-Astro/Microphysics pull request #1379
Opened 2023-10-29 23:10 UTC by zingale

2023-10-29 23:21 UTC, zingale commented
this will cause roundoff-level diffs

2023-10-30 00:28 UTC, yut23 requested changes
I checked everything with Mathematica, and sin5 has a sign error. All the others are correct.

2023-10-30 00:28 UTC, yut23 commented on neutrinos/sneut5.H
> +    const Real sin5 = sin1 * (5.0_rt - sin1 * sin1 * (20.0_rt + 16.0_rt * sin1 * sin1));
```suggestion
    const Real sin5 = sin1 * (5.0_rt - sin1 * sin1 * (20.0_rt - 16.0_rt * sin1 * sin1));
```

2023-10-30 18:04 UTC, yut23 approved these changes

2023-10-30 18:19 UTC, merged