Implement ISM chemistry including metals and dust
AMReX-Astro/Microphysics pull request #1642
Opened 2024-08-22 18:35 UTC by psharda

This PR will  build on the existing primordial ISM chemistry network to include a minimal network with metals and dust.

2024-08-22 20:56 UTC, psharda commented on EOS/primordial_chem/_parameters
> +species_1_name          string     "elec"
@zingale why does this change break the primordial chem test? I simply renamed the variable name from 'species_a_name' to 'species_1_name', and so on...

2024-08-22 21:22 UTC, zingale commented on EOS/primordial_chem/_parameters
> +species_1_name          string     "elec"
it seems that `make` returned a non-zero error code.  Maybe this is something you do in cmake?  It compiled fine, but `make` was not happy.

2024-08-26 18:36 UTC, psharda commented
@BenWibking do you understand why the metal_chem test failed?

2024-08-26 19:41 UTC, psharda commented
> @BenWibking do you understand why the metal_chem test failed? The overflow errors have been corrected now.

Ah nvm, I didn't upload the right file

2024-08-26 22:47 UTC, psharda commented
Everything else is good now, except for the CMake test. The test cannot find the Semenov opacity table (stored as a.dat file in networks/metal_chem). Any ideas @BenWibking ?

2024-08-27 14:00 UTC, BenWibking requested changes
Well, this is quite a lengthy PR. I did not review the boilerplate code.

There are a few things that can be improved in the interpolation and root-finding done for the dust temperature. Also, I think it's probably not necessary to keep commented-out code in the PR. It makes it even longer and harder to read. If it's there for debugging, you could put it in an `ifdef` instead.

2024-08-27 14:19 UTC, psharda commented
> Networks can be unavoidably very big, but IMHO we should find a way to avoid having 50,000+ line PRs to add new chemistry networks in the future.

How can you avoid it? You need everything in place to test the code out. Perhaps one alternative is to create _sub-PRs_ by dividing this PR into several chunks and merging them one by one. But there is no way of testing these sub-PRs, and no guarantee that all the chunks when merged would actually work. ISM chemistry in the presence of metals and dust is inherently complex, more so for our science goals that require going to very low metallicities. 

Note, however, that this is the _simplest_ network that works. FWIF future PRs that add cosmic rays and photochemistry will be smaller, since the base network is in place now.

2024-08-27 14:20 UTC, psharda commented
The YML tests also need to be done at all metallicities, not just one. As we have seen, the test might pass at one metallicity but not others.

2024-08-27 14:21 UTC, psharda commented on unit_test/burn_cell_metal_chem/burn_cell.H
> +
I wanted to keep the commented out code in question here until I have tried a simulation with quokka, as some of this might come in handy. Most of the code that I used to debug has been removed.

2024-08-27 14:23 UTC, psharda commented on networks/metal_chem/actual_rhs.H
> +
Done

2024-08-27 14:28 UTC, psharda commented on networks/metal_chem/actual_rhs.H
> +    while (true) {
Done

2024-08-27 14:41 UTC, BenWibking commented
> > Networks can be unavoidably very big, but IMHO we should find a way to avoid having 50,000+ line PRs to add new chemistry networks in the future.
> 
> How can you avoid it? You need everything in place to test the code out. Perhaps one alternative is to create _sub-PRs_ by dividing this PR into several chunks and merging them one by one. But there is no way of testing these sub-PRs, and no guarantee that all the chunks when merged would actually work. ISM chemistry in the presence of metals and dust is inherently complex, more so for our science goals that require going to very low metallicities _and_ high densities.
> 

There is a lot of duplicated code in the logic to test the outputs. That can be made simpler, or at least moved to a script that can be called each time. Also, the full reference outputs don't need to be saved in the repo: instead you can just save the final state and/or lines you want to compare.

2024-08-27 14:48 UTC, BenWibking commented
The main problem with the size of this PR comes from the 36,000 lines of the full reference outputs. You can instead save just the lines/numbers that you actually compare. Then it should be very manageable. The comparison might be easier to do as a Python script.

2024-08-27 15:47 UTC, BenWibking commented on unit_test/burn_cell_metal_chem/burn_cell.H
> +      break;
@zingale Is there some template or macro magic we can use to rewrite these very long `switch` statements?

2024-08-27 15:48 UTC, BenWibking commented on unit_test/burn_cell_metal_chem/burn_cell.H
> +                  state.xn[24] + state.xn[26] + state.xn[28] + state.xn[29] + state.xn[31];
Can you provide a function that users can call to do this? This has to be done in Quokka as well. This can be hard-coded, as long as it's in a function defined in each network that can be re-used.

2024-08-27 15:49 UTC, BenWibking commented on EOS/metal_chem/actual_eos.H
> +    }
It would be nice to replace this with template and/or macro magic if possible.

2024-08-27 16:30 UTC, zingale commented on unit_test/burn_cell_metal_chem/burn_cell.H
> +      break;
no, but there should be

2024-08-27 16:52 UTC, yut23 commented on unit_test/burn_cell_metal_chem/burn_cell.H
> +      break;
Is the loop and switch statement actually needed, or can you do this instead?
```cpp
amrex::Real numdens[NumSpec] = {
    primary_species_1,
    primary_species_2,
    primary_species_3,
    ...,
    primary_species_34
};
numdens[17 - 1] *= metal;
numdens[23 - 1] *= metal;
```
(if you want to allow `NumSpec` < 34, you could fill `amrex::Real primary_species[34]` instead then copy to `numdens`)

2024-08-27 17:08 UTC, yut23 commented on EOS/metal_chem/actual_eos.H
> +    }
I think a simple macro would work nicely here, along the lines of (untested)
```cpp
#define GET_SPECIES_PARAMS(num) do { \
    idx = network_spec_index(eos_rp::species_## num ##_name); \
    if (idx >= 0) { \
        gammas[idx] = eos_rp::species_## num ##_gamma; \
        spmasses[idx] = eos_rp::species_## num ##_mass; \
    } \
} while (0)

GET_SPECIES_PARAMS(1);
GET_SPECIES_PARAMS(2);
...
GET_SPECIES_PARAMS(34);

#undef GET_SPECIES_PARAMS
```

2024-08-27 17:21 UTC, zingale commented on unit_test/burn_cell_metal_chem/burn_cell.H
> +      break;
I don't think we want Boost as a dependency

2024-08-27 17:23 UTC, BenWibking commented on EOS/metal_chem/actual_eos.H
> +    }
You could even combine, e.g.:
```
#include <boost/preprocessor.hpp>

#define TO_SEQ_ELEM(z, n, data) (n)
#define MAKE_INTEGER_SEQUENCE(n) BOOST_PP_REPEAT(n, TO_SEQ_ELEM, )

MAKE_INTEGER_SEQUENCE(10) // (0) (1) (2) (3) (4) (5) (6) (7) (8) (9)
```

and then:

```
#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/seq/for_each.hpp>

#define SEQ (w)(x)(y)(z)

#define MACRO(r, data, elem) (elem, data)

BOOST_PP_SEQ_FOR_EACH(MACRO, _, SEQ) // expands to w_ x_ y_ z_
```

Then you don't even have to unroll `GET_SPECIES_PARAMS` manually.

2024-08-27 17:27 UTC, BenWibking commented on unit_test/burn_cell_metal_chem/burn_cell.H
> +      break;
I think this should work:
```
#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor.hpp>

#define TO_SEQ_ELEM(z, n, data) (n)
#define MAKE_INTEGER_SEQUENCE(n) BOOST_PP_REPEAT(n, TO_SEQ_ELEM, )
#define MACRO(r, data, elem) (data, elem)

// this expands to:  primary_species_0, primary_species_1, primary_species_2
BOOST_PP_SEQ_FOR_EACH(MACRO, primary_species_, MAKE_INTEGER_SEQUENCE(3)) 
```

2024-08-27 17:30 UTC, BenWibking commented on unit_test/burn_cell_metal_chem/burn_cell.H
> +      break;
> I don't think we want Boost as a dependency

Ah, ok. maybe we can run the preprocessor on the source and create a custom, specialized version of the macro?

2024-08-27 17:34 UTC, BenWibking commented on unit_test/burn_cell_metal_chem/burn_cell.H
> +      break;
Maybe we can copy-and-paste the implementation for this: https://github.com/HolyBlackCat/macro_sequence_for

2024-08-27 17:46 UTC, yut23 commented on unit_test/burn_cell_metal_chem/burn_cell.H
> +      break;
Personally, I find a bunch of lines that only differ by an incrementing number like this is simple enough to scan and check by eye, as long as they're all next to each other.

2024-08-27 17:51 UTC, BenWibking commented on unit_test/burn_cell_metal_chem/burn_cell.H
> +      break;
There's no good reason each network needs to repeat this boilerplate code at all. It could just be autogenerated based on the number of species.

2024-08-27 18:00 UTC, yut23 commented on unit_test/burn_cell_metal_chem/burn_cell.H
> +      break;
Another idea I had is to use ParmParse arrays and allow assignments to individual elements, like `unit_test.primary_species(1) = 1e-40`. That would require a bit of work in AMReX, but this seems like a pretty common pattern.

2024-08-27 18:03 UTC, BenWibking commented on unit_test/burn_cell_metal_chem/burn_cell.H
> +      break;
That should already work with `queryArr` if the array elements are separated by spaces, e.g.: `1e-40 1e-40 1e-10` etc.

2024-08-27 18:04 UTC, BenWibking commented on unit_test/burn_cell_metal_chem/burn_cell.H
> +      break;
I agree that using ParmParse to assign individual array elements would be more readable.

2024-08-27 19:56 UTC, psharda commented on EOS/metal_chem/actual_eos.H
> +    }
Added the macro. Thanks @yut23 for the suggestion!

2024-08-27 20:22 UTC, psharda commented on unit_test/burn_cell_metal_chem/burn_cell.H
> +                  state.xn[24] + state.xn[26] + state.xn[28] + state.xn[29] + state.xn[31];
I created a function in networks that can be called to do this.

2024-08-27 20:25 UTC, psharda commented on unit_test/burn_cell_metal_chem/burn_cell.H
> +      break;
> That would require a bit of work in AMReX, but this seems like a pretty common pattern.

So this is outside the scope of this PR?

2024-08-27 20:27 UTC, yut23 commented on unit_test/burn_cell_metal_chem/burn_cell.H
> +      break;
Yeah, we can come back to that later

2024-08-27 21:19 UTC, BenWibking commented on .github/workflows/burn_cell_metal_chem.yml
> +              sed -i 's/network.redshift = 0.0/network.redshift = 10.0/g' $modified_input_file
Instead of modifying the input file, you could just add the new input parameters on the command line. They should override those provided in the input file.

2024-08-27 21:19 UTC, BenWibking commented on EOS/primordial_chem/actual_eos.H
> +        spmasses[idx] = eos_rp::species_14_mass;
You could use the macro trick here, too.

2024-08-27 21:19 UTC, BenWibking commented on networks/metal_chem/actual_rhs.H
> +            throw std::runtime_error("Maximum iterations reached in dust temperature NR-solver. Tgas = " +
You can't throw exceptions on the GPU.

2024-08-27 21:19 UTC, BenWibking commented on networks/metal_chem/actual_rhs.H
> +    auto [x1_idx, x2_idx] = binary_search(xArray, x);
Is the Semenov table not equally-spaced in log density and log temperature?

2024-08-27 21:19 UTC, BenWibking commented on networks/metal_chem/actual_rhs.H
> +}
Up to you, but this file would be a lot easier to read if the cxxcode-generated function were in a separate header file.

2024-08-27 21:34 UTC, psharda commented on EOS/primordial_chem/actual_eos.H
> +        spmasses[idx] = eos_rp::species_14_mass;
Yes, but I thought lets do this (and charge balance) in a separate PR focused on the primordial chem network

2024-08-27 21:35 UTC, psharda commented on networks/metal_chem/actual_rhs.H
> +    auto [x1_idx, x2_idx] = binary_search(xArray, x);
no

2024-08-27 21:36 UTC, psharda commented on networks/metal_chem/actual_rhs.H
> +}
Can do it in a future PR

2024-08-27 21:39 UTC, psharda commented on .github/workflows/burn_cell_metal_chem.yml
> +              sed -i 's/network.redshift = 0.0/network.redshift = 10.0/g' $modified_input_file
yeah, that was the other choice. But they accomplish the same thing anyway.

2024-08-27 21:40 UTC, BenWibking commented on networks/metal_chem/actual_rhs.H
> +    auto [x1_idx, x2_idx] = binary_search(xArray, x);
hmm ok. this has to be done for every rhs evaluation, no? in the future, it might be worth considering resampling the table onto a uniform-log grid for performance.

2024-08-27 21:41 UTC, BenWibking commented on .github/workflows/burn_cell_metal_chem.yml
> +              sed -i 's/network.redshift = 0.0/network.redshift = 10.0/g' $modified_input_file
Yes, but this method is very hard to parse (pun intended).

2024-08-27 21:42 UTC, psharda commented on networks/metal_chem/actual_rhs.H
> +            throw std::runtime_error("Maximum iterations reached in dust temperature NR-solver. Tgas = " +
Will using `amrex::Error` like the rest of Microphysics suffice?

2024-08-27 21:44 UTC, psharda commented on networks/metal_chem/actual_rhs.H
> +    auto [x1_idx, x2_idx] = binary_search(xArray, x);
yes.
The opacity has a lot of kinks in particular temperature intervals (see the green curve in the attached plot), so the grid will have to be very dense throughout to maintain constant spacing.
[kappa_compare.pdf](https://github.com/user-attachments/files/16769944/kappa_compare.pdf)

2024-08-27 21:47 UTC, BenWibking commented on networks/metal_chem/actual_rhs.H
> +            throw std::runtime_error("Maximum iterations reached in dust temperature NR-solver. Tgas = " +
That might kill the whole code. It might be better to trigger the VODE retry mechanism. Not sure how to do that, but @zingale can tell us.

2024-08-28 13:12 UTC, BenWibking approved these changes
Looks good to me, but I'd still like @zingale to weight in on what the right thing to do about the in-line iterative solve for the dust temperature and how to handle convergence failure there.

2024-08-28 13:12 UTC, BenWibking commented on networks/metal_chem/actual_rhs.H
> +            amrex::Error("Maximum iterations reached in dust temperature NR-solver. Tgas = " +
Still not quite sure about what the right thing to do here is.

2024-08-28 15:26 UTC, zingale commented on networks/metal_chem/actual_rhs.H
> +            amrex::Error("Maximum iterations reached in dust temperature NR-solver. Tgas = " +
in general, we don't abort in the nets, but instead set a failure for the application code to interpret,
`burn_t.success`

As an aside, if you really need 1000 iterations, maybe NR is not up to the task?  Have you tried the hybrid Powell solver (that's what scipy.fsolve() uses): https://github.com/AMReX-Astro/Microphysics/tree/main/util/hybrj

2024-08-29 12:52 UTC, psharda commented on networks/metal_chem/actual_rhs.H
> +            amrex::Error("Maximum iterations reached in dust temperature NR-solver. Tgas = " +
We do not need 1000 iterations in general. For the tests, the max iterations taken are  ~unity. If we reach 1000 iterations, then something has probably gone wrong.

I see that the max iterations in the hybrid Powell solver is also set to 1000?

Can this be an issue for future work, and not a part of this PR?

2024-08-29 12:53 UTC, psharda commented on networks/metal_chem/_parameters
> +idx_gas_species                int                0
Just FYI @BenWibking we need this newly added parameter in quokka, because we need mass fractions there.

2024-08-29 14:41 UTC, BenWibking commented on networks/metal_chem/actual_rhs.H
> +            amrex::Error("Maximum iterations reached in dust temperature NR-solver. Tgas = " +
Keeping the Newton solver sounds fine. However, is it possible to set `burn_t.success = 0` here? If it's currently not possible to set the failure condition within actual_rhs, then I'm fine with things as-is in this PR.

2024-08-29 15:22 UTC, psharda commented on networks/metal_chem/actual_rhs.H
> +            amrex::Error("Maximum iterations reached in dust temperature NR-solver. Tgas = " +
Maybe we can. I can pass the burn_t object to this function, and make it return state.success. So when it is called by `actual_rhs`, state.success would be set to false. Perhaps the rest of the microphysics machinery can then take that into account? 

But I would rather leave this as it is for now, and work on it later when there is more time (after the job season).

2024-08-29 17:29 UTC, merged